name = "music"
main = "src/index.js"
compatibility_date = "2024-12-18"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "telegram-music-db"
database_id = "1826893b-c4ab-458e-a195-93e40ebef074"

# Variables (these will be secrets in production)
[vars]
SITE_DOMAIN = "music.zedtopvibes.com"

# Routes
[[routes]]
pattern = "music.zedtopvibes.com"